![alt text](https://i.imgur.com/1WaY7aA.png)


---



---



# Lab 3.1.1 
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [2]:
import numpy as np
import pandas as pd

*It is good practice to display the library version numbers for future reference:*

In [3]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.16.2
Pandas:  0.24.2


### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [4]:
# wrong:
bikes = pd.read_table('../DATA/bikeshare.csv', header = None)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('../DATA/bikeshare.csv', header = 1)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('../DATA/bikeshare.csv', header = 0)
print(bikes.head())

                                                   0
0  instant,dteday,season,yr,mnth,hr,holiday,weekd...
1  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...
2  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...
3  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...
4  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...

  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0,3,13,16
0  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...     
1  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...     
2  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...     
3  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...     
4  6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,...     

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                        

C:\Users\Beau\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  
C:\Users\Beau\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  import sys
C:\Users\Beau\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  if sys.path[0] == '':


?:
ANSWER: Case 1 treats headings as just another data row. Case 2 treats the 1st data row as the column header. Case 3 gets the header right (row 0), but reads each row as a single column (Nb. the other two make that same mistake). 

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [5]:
#ANSWER:
bikes = pd.read_csv('../DATA/bikeshare.csv', '\t',header = 0)
print(bikes.head())
print()

  instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0  1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,...                                                                   
1  2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0...                                                                   
2  3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.8,0...                                                                   
3  4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,...                                                                   
4  5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,...                                                                   



Note that we could have used `read.csv()` above. When is `read_table()` necessary?

?:
ANSWER: When `sep` is not the comma character, or we need fine control that `read.csv()` does not provide.

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects 
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be delth with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [6]:
from pandas import ExcelFile  # Nb. Need to install xlrd from conda (it does not automatically install with pandas)

In [7]:
df = pd.read_excel('../DATA/Iris.xls', sheet_name = 'Iris')
df

XLRDError: No sheet named <'Iris'>

So, this file appears to have an embedded table of aggregates on the same sheet as the raw data (a naughty but common practice amongst analysts).

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For ecxample, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [8]:
# What are the unwanted columns?
#ANSWER
df = pd.read_excel('../DATA/Iris.xls', sheet_name = 'Data')
df.head()

Species_No  Petal_width  Petal_length  Sepal_width  Sepal_length  \
0           1          0.2           1.4          3.5           5.1   
1           1          0.2           1.4          3.0           4.9   
2           1          0.2           1.3          3.2           4.7   
3           1          0.2           1.5          3.1           4.6   
4           1          0.2           1.4          3.6           5.0   

  Species_name  
0       Setosa  
1       Setosa  
2       Setosa  
3       Setosa  
4       Setosa

### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [9]:
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_hour.csv')
df.head()

Empty DataFrame
Columns: [time, latitude, longitude, depth, mag, magType, nst, gap, dmin, rms, net, id, updated, place, type, horizontalError, depthError, magError, magNst, status, locationSource, magSource]
Index: []

[0 rows x 22 columns]

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [10]:
url = 'http://www.fdic.gov/bank/individual/failed/banklist.html'
df = pd.read_html(url)
df

[                                             Bank Name                City  \
 0                                 The Enloe State Bank              Cooper   
 1                  Washington Federal Bank for Savings             Chicago   
 2      The Farmers and Merchants State Bank of Argonia             Argonia   
 3                                  Fayette County Bank          Saint Elmo   
 4    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
 5                                       First NBC Bank         New Orleans   
 6                                        Proficio Bank  Cottonwood Heights   
 7                        Seaway Bank and Trust Company             Chicago   
 8                               Harvest Community Bank          Pennsville   
 9                                          Allied Bank            Mulberry   
 10                        The Woodbury Banking Company            Woodbury   
 11                              First CornerStone B

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here is an example that includes a nice parser class: http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

#### Importing JSON Files from the Web

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example: 

In [11]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame
df = pd.read_json(url, orient = 'columns')
df.head()

integer            datetime  category
0         5 2015-01-01 00:00:00         0
1         5 2015-01-01 00:00:01         0
10        5 2015-01-01 00:00:10         0
11        5 2015-01-01 00:00:11         0
12        8 2015-01-01 00:00:12         0

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table


### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [12]:
#ANSWER
bikes = pd.read_csv('../DATA/bikeshare.csv')
bikes.shape



(17379, 17)

What are the column names in `bikes`?

In [13]:
#ANSWER
bikes.columns


Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

What are the data types of these columns?

In [14]:
#ANSWER
bikes.dtypes

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

What is the (row) index for this DataFrame?

In [15]:
#ANSWER
bikes.index

RangeIndex(start=0, stop=17379, step=1)

https://www.dataquest.io/blog/python-json-tutorial/

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this. 
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [16]:
#ANSWER
# bikes['season'] # --> returns a series
bikes[['season']] # --> returns a dataframe

season
0           1
1           1
2           1
3           1
4           1
5           1
6           1
7           1
8           1
9           1
10          1
11          1
12          1
13          1
14          1
15          1
16          1
17          1
18          1
19          1
20          1
21          1
22          1
23          1
24          1
25          1
26          1
27          1
28          1
29          1
...       ...
17349       1
17350       1
17351       1
17352       1
17353       1
17354       1
17355       1
17356       1
17357       1
17358       1
17359       1
17360       1
17361       1
17362       1
17363       1
17364       1
17365       1
17366       1
17367       1
17368       1
17369       1
17370       1
17371       1
17372       1
17373       1
17374       1
17375       1
17376       1
17377       1
17378       1

[17379 rows x 1 columns]

How would we use object notation to show the first 4 rows of `atemp`?

In [17]:
#ANSWER
# atemp[:4]
bikes[:4]

instant      dteday  season  yr  mnth  hr  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1   0        0        6           0   
1        2  2011-01-01       1   0     1   1        0        6           0   
2        3  2011-01-01       1   0     1   2        0        6           0   
3        4  2011-01-01       1   0     1   3        0        6           0   

   weathersit  temp   atemp   hum  windspeed  casual  registered  cnt  
0           1  0.24  0.2879  0.81        0.0       3          13   16  
1           1  0.22  0.2727  0.80        0.0       8          32   40  
2           1  0.22  0.2727  0.80        0.0       5          27   32  
3           1  0.24  0.2879  0.75        0.0       3          10   13

Algorithms that loop over multiple columns often access DataFrame columns by index. However, none of the following work (try them out by uncommenting / removing the "#E: " ): 

In [18]:
#bikes[[0]]
#bikes[0]
#bikes[0,0]
bikes[[0,0]]

KeyError: "None of [Int64Index([0, 0], dtype='int64')] are in the [columns]"

What is the correct way to access the 1st row of the DataFrame by its index?

In [19]:
#ANSWER
bikes.iloc[0]

instant                1
dteday        2011-01-01
season                 1
yr                     0
mnth                   1
hr                     0
holiday                0
weekday                6
workingday             0
weathersit             1
temp                0.24
atemp             0.2879
hum                 0.81
windspeed              0
casual                 3
registered            13
cnt                   16
Name: 0, dtype: object

What is the correct way to access the 2nd column of the DataFrame by its index?

In [20]:
#ANSWER
bikes.iloc[1]

instant                2
dteday        2011-01-01
season                 1
yr                     0
mnth                   1
hr                     1
holiday                0
weekday                6
workingday             0
weathersit             1
temp                0.22
atemp             0.2727
hum                  0.8
windspeed              0
casual                 8
registered            32
cnt                   40
Name: 1, dtype: object

## Handling Missing Values

What is the Pandas `isnull` function for? 

?
ANSWER: 

Counts the number of Null values in the each series of the dataframe.

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [21]:
bikes.isnull().head()

instant  dteday  season     yr   mnth     hr  holiday  weekday  workingday  \
0    False   False   False  False  False  False    False    False       False   
1    False   False   False  False  False  False    False    False       False   
2    False   False   False  False  False  False    False    False       False   
3    False   False   False  False  False  False    False    False       False   
4    False   False   False  False  False  False    False    False       False   

   weathersit   temp  atemp    hum  windspeed  casual  registered    cnt  
0       False  False  False  False      False   False       False  False  
1       False  False  False  False      False   False       False  False  
2       False  False  False  False      False   False       False  False  
3       False  False  False  False      False   False       False  False  
4       False  False  False  False      False   False       False  False

However, we usually start at a higher level. How many nulls are in `bikes` altogether?

In [22]:
#ANSWER
bikes.isnull().sum().sum()

0

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [23]:
#ANSWER
bikes.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

What is the Numpy object `nan` used for? (Write a descriptive answer.)

?
ANSWER: Marking a data point as invalid.

Write (and verify) a function that performs scalar division with built-in handling of the edge case (i.e. return a value instead of just trapping the error):

In [24]:
#ANSWER
def scalar_div(a,b):
    try: 
        return a/b
    except:
        return 0
    
    
print (scalar_div(5,0))
print (scalar_div(np.nan,2))
print (scalar_div(5,np.nan))
print (scalar_div(40,2))
    

0
nan
nan
20.0


Apply the Pandas `isna` function to the following data objects:

In [25]:
x = 2.3
y = np.nan
print(x, y)

2.3 nan


In [26]:
#ANSWER
print (x.isna())
print (y.isna())

AttributeError: 'float' object has no attribute 'isna'

In [27]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(array)

[[ 1. nan  3.]
 [ 4.  5. nan]]


In [28]:
#ANSWER
array.isna()

AttributeError: 'numpy.ndarray' object has no attribute 'isna'

**Note:** The `isna()` attribute is not available for a float or numpy object. Only for pandas objects

____
How is the pandas I/O parameter `na_values` used?

? ANSWER: 

Indicates if any other specific characteres should be recognised as null values

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [28]:
#ANSWER
bikes['season'].unique()

array([1, 2, 3, 4], dtype=int64)

### Ranges

Print the range of the `instant`, `dteday`, and `windspeed` columns: 

In [29]:
#ANSWER
#bikes[['instant','dteday','windspeed']].describe()
print ("minimum: ")
print (bikes[['instant','dteday','windspeed']].min())



minimum: 
instant               1
dteday       2011-01-01
windspeed             0
dtype: object


In [30]:
print ("maximum: ")
print (bikes[['instant','dteday','windspeed']].max())

maximum: 
instant           17379
dteday       2012-12-31
windspeed        0.8507
dtype: object


Compute and print the overall minimum and maximum of the numeric data columns:

In [31]:
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']


bikes_min, bikes_max = (min(bikes.select_dtypes(include=numerics).min()), max(bikes.select_dtypes(include=numerics).max()))
bikes_min, bikes_max

(0.0, 17379.0)

### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [32]:
bikes['atemp'].quantile(0.5)

0.4848

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code: 

In [33]:
#ANSWER
print ("10% quantile: ",bikes['atemp'].quantile(0.1))
print ("25% quantile: ",bikes['atemp'].quantile(0.25))
print ("50% quantile: ",bikes['atemp'].quantile(0.5))
print ("70% quantile: ",bikes['atemp'].quantile(0.7))
print ("90% quantile: ",bikes['atemp'].quantile(0.9))


10% quantile:  0.2424
25% quantile:  0.3333
50% quantile:  0.4848
70% quantile:  0.6061
90% quantile:  0.6970000000000001


### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [34]:
type(bikes['atemp'])

pandas.core.series.Series

In [35]:
bikes.sample(5)

instant      dteday  season  yr  mnth  hr  holiday  weekday  \
3102      3103  2011-05-14       2   0     5   4        0        6   
12771    12772  2012-06-21       3   1     6   8        0        4   
2939      2940  2011-05-07       2   0     5   9        0        6   
7591      7592  2011-11-17       4   0    11  22        0        4   
2923      2924  2011-05-06       2   0     5  17        0        5   

       workingday  weathersit  temp   atemp   hum  windspeed  casual  \
3102            0           2  0.50  0.4848  0.82     0.1642       1   
12771           1           1  0.74  0.6970  0.70     0.0000      27   
2939            0           1  0.54  0.5152  0.49     0.2836      54   
7591            1           1  0.26  0.2424  0.52     0.2537       1   
2923            1           1  0.58  0.5455  0.40     0.3582      83   

       registered  cnt  
3102            4    5  
12771         563  590  
2939          164  218  
7591           83   84  
2923          470  553

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indcates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [36]:
atemp_level = pd.cut(bikes['atemp'], bins = 4)         

What is `atemp_level`?

#### ANSWER

a list of tuples containing the boundaries of the bins

Here is a random sample of `atemp_level`:

In [37]:
atemp_level.sample(5)          

11654    (0.5, 0.75]
10128    (0.25, 0.5]
7797     (0.25, 0.5]
1874     (0.25, 0.5]
12437    (0.5, 0.75]
Name: atemp, dtype: category
Categories (4, interval[float64]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [38]:
atemp_level = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level.sample(5)          

5438     warm
17019    mild
2395     warm
6708     warm
3004     mild
Name: atemp, dtype: category
Categories (4, object): [cool < mild < warm < hot]

Incorporate the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [39]:
#ANSWER
bikes['atemp_level'] = atemp_level
bikes.groupby(by='season').count()['atemp']


season
1    4242
2    4409
3    4496
4    4232
Name: atemp, dtype: int64

*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

# Synthetic Data

Sometimes we may want to generate test data, or we may need to initalise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [40]:
# Creating arrays with initial values
a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,4))   # randint(low, high, size)
d = np.arange(4)
e = np.array( [[1,2,3,4], [5,6,7,8]] )

In [41]:
print (a.shape)
print (b.shape)
print (c.shape)
print (d.shape)
print (e.shape)


(3,)
(1, 3)
(2, 3, 4)
(4,)
(2, 4)


In [42]:
print ('a')
print (a)
print ('b')
print (b)
print ('c')
print (c)
print ('d')
print (d)
print ('e')
print (e)


a
[0. 0. 0.]
b
[[1. 1. 1.]]
c
[[[1 6 4 4]
  [6 4 9 2]
  [1 6 1 5]]

 [[8 3 5 3]
  [3 6 1 7]
  [9 1 5 2]]]
d
[0 1 2 3]
e
[[1 2 3 4]
 [5 6 7 8]]


# Cleaning Data

## Load Data

Load rock.csv and clean the dataset.

In [47]:
rock = pd.read_csv('../DATA/rock.csv')

## Check Column Names

Check column names and clean.

In [48]:
rock.columns

Index(['Song Clean', 'ARTIST CLEAN', 'Release Year', 'COMBINED', 'First?',
       'Year?', 'PlayCount', 'F*G'],
      dtype='object')

# Replace Null Values With 0

Check 'release' column whether this column have any null value or not. Replace null value with 0.

In [49]:
rock.isnull().sum()

Song Clean        0
ARTIST CLEAN      0
Release Year    577
COMBINED          0
First?            0
Year?             0
PlayCount         0
F*G               0
dtype: int64

In [50]:
rock.fillna(0, inplace=True)

# Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column. 

In [51]:
rock.dtypes

Song Clean      object
ARTIST CLEAN    object
Release Year    object
COMBINED        object
First?           int64
Year?            int64
PlayCount        int64
F*G              int64
dtype: object

In [66]:
#rock['Release Year'].astype('int') # --> produces error because 1 item has 'SONGFACTS.COM' in the year.
rock[rock['Release Year'] == 'SONGFACTS.COM']

Empty DataFrame
Columns: [Song Clean, ARTIST CLEAN, Release Year, COMBINED, First?, Year?, PlayCount, F*G]
Index: []

# Check Min, Max of Each Column

Is there any illogical value in any column? How can we fix that?

In [53]:
rock.min()

Song Clean                     #9 Dream
ARTIST CLEAN                .38 Special
COMBINED        #9 Dream by John Lennon
First?                                1
Year?                                 0
PlayCount                             0
F*G                                   0
dtype: object

In [54]:
rock.max()

Song Clean                     Ziggy Stardust
ARTIST CLEAN                             a-ha
COMBINED        Ziggy Stardust by David Bowie
First?                                      1
Year?                                       1
PlayCount                                 142
F*G                                       142
dtype: object

In [55]:
# We will fix this issue
rock['Release Year'][rock['Release Year'] == 'SONGFACTS.COM'] = 0
rock['Release Year'] = rock['Release Year'].astype('int')

C:\Users\Beau\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


# Write Some Functions

## Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [56]:
def is_release_lt_1970(df):
    if (df['Release Year'] < 1970):
        return True
    else:
        return False

def display_details(df_row):
    is_release_lt_1970(df_row)
    print ("Song: ",df_row['Song Clean'])
    print ("Artist: ",df_row['ARTIST CLEAN'])
    print ("Release < 1970: ",is_release_lt_1970(df_row))



## Write a function that converts cells in a DataFrame to float and otherwise replaces them with np.nan

In [57]:
def cast_to_float(df):
    for col in df.columns:
        
        try:
            df[col] = df[col].astype('float')
        except:
            df[col] = np.nan

    return df
    

## Apply these functions to your dataset

In [58]:
display_details(rock.iloc[0])
display_details(rock.iloc[10])
display_details(rock.iloc[20])
display_details(rock.iloc[50])

float_rock = cast_to_float(rock)

Song:  Caught Up in You
Artist:  .38 Special
Release < 1970:  False
Song:  Baby, Please Don't Go
Artist:  AC/DC
Release < 1970:  True
Song:  Highway To Hell
Artist:  AC/DC
Release < 1970:  False
Song:  Dude (Looks Like a Lady)
Artist:  Aerosmith
Release < 1970:  False


## Describe the new float-only DataFrame.

In [59]:
float_rock.describe()

Song Clean  ARTIST CLEAN  Release Year  COMBINED  First?        Year?  \
count         0.0           0.0   2230.000000       0.0  2230.0  2230.000000   
mean          NaN           NaN   1465.331390       NaN     1.0     0.741256   
std           NaN           NaN    867.196161       NaN     0.0     0.438043   
min           NaN           NaN      0.000000       NaN     1.0     0.000000   
25%           NaN           NaN      0.000000       NaN     1.0     0.000000   
50%           NaN           NaN   1973.000000       NaN     1.0     1.000000   
75%           NaN           NaN   1981.000000       NaN     1.0     1.000000   
max           NaN           NaN   2014.000000       NaN     1.0     1.000000   

         PlayCount          F*G  
count  2230.000000  2230.000000  
mean     16.872646    15.048430  
std      25.302972    25.288366  
min       0.000000     0.000000  
25%       1.000000     0.000000  
50%       4.000000     3.000000  
75%      21.000000    18.000000  
max     142.000000   142.000000



> 
>
>




>


>


>




---



---

> > > > > > > >   © 2019 Data Science Institute of Australia


---



---

